---
# file: roles/common/tasks/prerequisites.yaml

- name: Jenkins Prerequisites
  hosts: jenkins_server
  become: true
    tasks:

    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Update repository and install Java
      ansible.builtin.apt:
        update_cache: true
        pkg:
        - fontconfig
        - openjdk-17-jre
        - docker.io

- name: Download jenkins keyring into APT
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Update APT sources list
  shell:
    cmd: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/jenkins.list

- name: Install the latest version of Jenkins
  ansible.builtin.apt:
    update_cache: true
    name: jenkins
    state: present

- name: Fetch jenkins initial admin password
  ansible.builtin.fetch:
    src: /var/lib/jenkins/secrets/initialAdminPassword
    dest: fetch/{{ inventory_hostname }}/initialAdminPassword
    flat: yes

- name: Grant Jenkins user permission to docker deamon.
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes

- name: Grant Ubuntu user permission to docker deamon.
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes

- name: Restart docker
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: docker